# -*- coding: utf-8 -*-
"""RS1_yield.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KoTad1tgzD_t-b7JLAeE5OqkURfDagz8
"""

import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

# Load dataset
df=pd.read_csv('/content/RS-A1_yield.csv')
print(df.head(5))
print(df.columns)
# Handle missing values
imputer_num = SimpleImputer(strategy='mean')
imputer_cat=SimpleImputer(strategy='most_frequent')
df[['average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']] = imputer_num.fit_transform(df[['average_rain_fall_mm_per_year', 'pesticides_tonnes', 'avg_temp']])
df[['Area','Item']] = imputer_cat.fit_transform(df[['Area','Item']])
# Encode categorical variables
le_area=LabelEncoder()
le_item=LabelEncoder()
df['Item']=le_item.fit_transform(df['Item'])
df['Area']=le_area.fit_transform(df['Area'])
# Define features and target variable
x=df[['Area','Item','average_rain_fall_mm_per_year','pesticides_tonnes','avg_temp']]
y=df['hg/ha_yield']
# Split the dataset
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
rf=RandomForestRegressor(n_estimators=100,random_state=42)
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print(f"Mean Squared Error: {mse}")
print(f"R^2 Score: {r2}")
plt.scatter(y_test,y_pred)
plt.xlabel("Actual Yields")
plt.ylabel("Predicted Yields")
plt.title("Actual vs Predicted Yields")
plt.show()

X_train_images = np.random.rand(100, 64, 64, 3) # Random 100 RGB images
y_train_images = np.random.randint(2, size=100) # Random binary labels (0: Healthy, 1: Diseased)
# CNN Model for Disease Detection
cnn_model = Sequential()
cnn_model.add(Conv2D(32, (3, 3), input_shape=(64, 64, 3), activation='relu'))
cnn_model.add(MaxPooling2D(pool_size=(2, 2)))
cnn_model.add(Flatten())
cnn_model.add(Dense(128, activation='relu'))
cnn_model.add(Dense(1, activation='sigmoid')) # Output layer for binary classification
# Compile the CNN model
cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# Train the CNN model (using mock data, real images should be used in practice)
cnn_model.fit(X_train_images, y_train_images, epochs=5, batch_size=10, verbose=1)
# Evaluate the CNN model
loss, accuracy = cnn_model.evaluate(X_train_images, y_train_images, verbose=0)
print(f"CNN Model Accuracy: {accuracy}")

from google.colab import files

print("Please upload an image file for disease detection:")
uploaded_files = files.upload()

# Get the filename of the first uploaded image
if uploaded_files:
    filename = next(iter(uploaded_files))
    print(f"Uploaded file: {filename}")
else:
    print("No file was uploaded.")

from PIL import Image

if 'filename' in locals() and filename:
    try:
        # Open the image
        img = Image.open(filename)

        # Resize the image to 64x64
        img = img.resize((64, 64))

        # Convert to RGB (if not already)
        img = img.convert('RGB')

        # Convert image to numpy array and normalize pixel values
        img_array = np.array(img) / 255.0  # Normalize to [0, 1]

        # Add batch dimension (1, 64, 64, 3) for the model
        img_array = np.expand_dims(img_array, axis=0)

        print(f"Processed image shape: {img_array.shape}")

        # Make prediction using the CNN model
        prediction = cnn_model.predict(img_array)

        # Interpret the prediction
        if prediction[0][0] > 0.5:
            status = "Diseased"
        else:
            status = "Healthy"

        print(f"The uploaded crop is predicted to be: {status} (confidence: {prediction[0][0]:.4f})")

    except Exception as e:
        print(f"Error processing image: {e}")
else:
    print("No image file found for processing. Please upload an image first.")

print("Please enter the following values for crop yield prediction:")

# Get user input for Area and Item
user_area = input("Enter Area (e.g., India, China): ")
user_item = input("Enter Item (e.g., Maize, Wheat): ")

# Get user input for numerical features and convert to float
try:
    user_rain_fall = float(input("Enter average_rain_fall_mm_per_year: "))
    user_pesticides = float(input("Enter pesticides_tonnes: "))
    user_avg_temp = float(input("Enter avg_temp: "))
except ValueError:
    print("Invalid input for numerical fields. Please enter numbers.")
    user_rain_fall = None
    user_pesticides = None
    user_avg_temp = None

if all([user_rain_fall is not None, user_pesticides is not None, user_avg_temp is not None]):
    print("\nUser Inputs:")
    print(f"Area: {user_area}")
    print(f"Item: {user_item}")
    print(f"Average Rain Fall (mm/year): {user_rain_fall}")
    print(f"Pesticides (tonnes): {user_pesticides}")
    print(f"Average Temperature: {user_avg_temp}")
else:
    print("Input collection failed due to invalid numerical entries.")

if all([user_rain_fall is not None, user_pesticides is not None, user_avg_temp is not None]):
    try:
        # Encode categorical inputs
        encoded_area = le_area.transform([user_area])[0]
        encoded_item = le_item.transform([user_item])[0]

        # Create a DataFrame for prediction, matching the structure of x_train
        user_input_df = pd.DataFrame({
            'Area': [encoded_area],
            'Item': [encoded_item],
            'average_rain_fall_mm_per_year': [user_rain_fall],
            'pesticides_tonnes': [user_pesticides],
            'avg_temp': [user_avg_temp]
        })

        # Predict yield
        predicted_yield = rf.predict(user_input_df)

        print(f"\nPredicted Crop Yield (hg/ha): {predicted_yield[0]:.2f}")

    except ValueError as e:
        print(f"Error: One or more categorical inputs ('Area' or 'Item') are not recognized by the model. Please check your spelling or input an area/item that was part of the training data. Details: {e}")
    except Exception as e:
        print(f"An unexpected error occurred during prediction: {e}")
else:
    print("Cannot predict yield due to missing or invalid numerical inputs.")

"""
# --- Step 3: Recommendation System --
# ==============================================
def recommend(disease_prediction, yield_prediction):
  if disease_prediction >= 0.5:
    return "Disease detected! Recommended action: Apply pesticide."
  elif yield_prediction < 50:
    return "Low yield predicted! Recommended action: Improve irrigation and soil quality."
  else:
    return "Crop is healthy and yield prediction is optimal."


# --- Step 4: Testing the System --
# ==============================================
import random, os
from keras.preprocessing import image
test_class = random.choice(['healthy', 'diseased'])
test_dir = os.path.join(dataset_path, test_class)
test_img_path = '/content/Gemini_Generated_Image_lxa0l3lxa0l3lxa0.png'

img = image.load_img(test_img_path, target_size=(64, 64))
img_array = image.img_to_array(img) / 255.0
img_array = np.expand_dims(img_array, axis=0)

# CNN prediction
disease_prediction = cnn_model.predict(img_array)[0][0]
# Simulated environmental data for yield model
test_env_data = np.array([[0.8, 0.6, 0.7]])  # rainfall, temp, soil quality
yield_prediction = yield_model.predict(test_env_data)[0]
# Generate recommendation
recommendation = recommend(disease_prediction, yield_prediction)

"""