# -*- coding: utf-8 -*-
"""RS-5Ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pLQFTUVJApU1_ZhNQUKTXXGmo4abM1Lq

# Task
Build a recommendation system using the dataset `/content/RS-A5_amazon_products_sales_data_cleaned.csv`. In this system, treat `product_title` as the user-like entity, `product_category` as the item category, and `product_rating` as the interaction score. Preprocess the data by dropping missing values in these columns and scaling `product_rating` to a `Purchase_Score` between 0 and 1. Create a 'Product-Category Matrix', apply Truncated SVD to generate latent factors, and then reconstruct the matrix to obtain and display predicted interaction scores (`predicted_df`). Finally, implement a function to provide Top-N `product_category` recommendations for a given `product_title` and demonstrate its use with a sample product, ensuring all requirements are met.

## Load New Dataset and Identify Columns

### Subtask:
Load the `/content/RS-A5_amazon_products_sales_data_cleaned.csv` dataset and confirm the presence of `product_title`, `product_category`, and `product_rating` columns.

**Reasoning**:
Load the dataset into a pandas DataFrame, display its head, and verify the presence of the required columns.
"""

import pandas as pd

# Load the dataset
df_new = pd.read_csv('/content/RS-A5_amazon_products_sales_data_cleaned.csv')

# Display the first few rows
print("First 5 rows of the DataFrame:")
print(df_new.head())

# Verify the presence of required columns
required_columns = ['product_title', 'product_category', 'product_rating']
missing_columns = [col for col in required_columns if col not in df_new.columns]

if not missing_columns:
    print(f"\nAll required columns {required_columns} are present in the DataFrame.")
else:
    print(f"\nMissing columns: {missing_columns}")

"""## Adjust Preprocessing and Create Product-Category Matrix

### Subtask:
Perform data preprocessing by dropping missing values in key columns, scaling `product_rating` to a `Purchase_Score`, and then constructing a 'Product-Category Matrix'.

**Reasoning**:
First, I'll drop rows with missing values in the specified columns to ensure data quality. Then, I'll calculate the min and max of the 'product_rating' column, which is essential for the min-max scaling to transform 'product_rating' into a 'Purchase_Score' between 0 and 1. Finally, I'll create the 'Product-Category Matrix' using a pivot table, filling NaN values with 0 to represent no interaction, as specified in the instructions.
"""

import numpy as np

# 1. Drop rows with missing values in the specified columns
df_processed = df_new.dropna(subset=['product_title', 'product_category', 'product_rating']).copy()
print(f"Shape after dropping NaNs: {df_processed.shape}")

# 2. Calculate the minimum and maximum values of the product_rating column
min_rating = df_processed['product_rating'].min()
max_rating = df_processed['product_rating'].max()
print(f"Minimum product_rating: {min_rating}, Maximum product_rating: {max_rating}")

# 3. Scale the product_rating column to create a new column called Purchase_Score
# Handle the case where max_rating == min_rating to avoid division by zero
if max_rating == min_rating:
    df_processed['Purchase_Score'] = 0.5  # Assign a neutral score if all ratings are the same
else:
    df_processed['Purchase_Score'] = (df_processed['product_rating'] - min_rating) / (max_rating - min_rating)

print("First 5 rows with Purchase_Score:")
print(df_processed[['product_title', 'product_category', 'product_rating', 'Purchase_Score']].head())

# 4. Create a 'Product-Category Matrix'
product_category_matrix = df_processed.pivot_table(
    index='product_title',
    columns='product_category',
    values='Purchase_Score',
    fill_value=0
)

print("\nShape of Product-Category Matrix:")
print(product_category_matrix.shape)
print("\nFirst 5 rows of Product-Category Matrix:")
print(product_category_matrix.head())

"""## Apply SVD and Display Predicted Scores

### Subtask:
Apply Truncated SVD to the 'Product-Category Matrix' to generate latent factors. Then, reconstruct the matrix to obtain `predicted_df`, which will contain the predicted interaction scores for all product-category pairs. A sample of this `predicted_df` will be explicitly displayed to demonstrate the 'Predicted Scores'.

**Reasoning**:
I will import TruncatedSVD, apply it to the `product_category_matrix` to generate latent factors, reconstruct the matrix to get predicted scores, convert it to a DataFrame, and display the first few rows to show the results.
"""

from sklearn.decomposition import TruncatedSVD

# Number of latent factors (components)
# This should be less than the number of features (product categories)
num_features = product_category_matrix.shape[1]
n_components = min(14, num_features - 1) # Changed n_components to a higher value to capture more variance

print(f"Number of product categories (features): {num_features}")
print(f"Number of SVD components to use: {n_components}")

# Initialize TruncatedSVD model
svd = TruncatedSVD(n_components=n_components, random_state=42)

# Fit SVD to the Product-Category Matrix and transform it
latent_matrix = svd.fit_transform(product_category_matrix)

print(f"Shape of latent_matrix (product_title x latent_factors): {latent_matrix.shape}")

# Reconstruct the matrix to get predicted interaction scores
# latent_matrix (U_k * S_k) and svd.components_ (V_k.T)
predicted_matrix = np.dot(latent_matrix, svd.components_)

print(f"Shape of predicted_matrix: {predicted_matrix.shape}")

# Convert the reconstructed matrix into a pandas DataFrame
predicted_df = pd.DataFrame(predicted_matrix,
                              columns=product_category_matrix.columns,
                              index=product_category_matrix.index)

# Display the first few rows of the predicted_df
print("\nFirst 5 rows of Predicted Interaction Scores (predicted_df):")
print(predicted_df.head())

"""## Generate and Display Top-N Product Category Recommendations

### Subtask:
Define and utilize a recommendation function that takes a `product_title` and returns the top-N `product_category` recommendations based on the predicted interaction scores from the `predicted_df`. This function will filter out categories that the product is already associated with. The top-N product category recommendations for a sample product will then be generated and explicitly printed.

**Reasoning**:
I will define the `recommend_categories` function as per the instructions, retrieve a sample product title, call the function with the sample product and N=5, and then print the generated recommendations.
"""

def recommend_categories(product_title, predicted_df, product_category_matrix, n=5):
    # Check if the product_title exists in the predicted_df index
    if product_title not in predicted_df.index:
        return f"Product title '{product_title}' not found in the predicted matrix."

    # Get predicted scores for the given product
    product_predictions = predicted_df.loc[product_title]

    # Get categories the product is already associated with from the original matrix
    # Categories with a Purchase_Score > 0 are considered associated
    associated_categories = product_category_matrix.loc[product_title][product_category_matrix.loc[product_title] > 0].index

    # Filter out categories that the product is already associated with
    filtered_predictions = product_predictions.drop(associated_categories, errors='ignore')

    # Sort the remaining predicted categories by their scores in descending order
    top_n_recommendations = filtered_predictions.sort_values(ascending=False).head(n)

    return top_n_recommendations

# Choose a sample product_title
# Ensure the chosen product_title exists in the index of product_category_matrix
sample_product_title = product_category_matrix.index[0] # Using the first product title as an example
print(f"Sample product title for recommendation: {sample_product_title}")

# Generate Top-N recommendations
N = 5
recommendations = recommend_categories(sample_product_title, predicted_df, product_category_matrix, N)

# Print the recommendations
print(f"\nTop {N} product category recommendations for '{sample_product_title}':")
if isinstance(recommendations, str):
    print(recommendations)
else:
    for category, score in recommendations.items():
        print(f"- {category}: {score}") # Showing raw scores without rounding

"""## Final Task

### Subtask:
Confirm that the model has been trained, the predicted scores for product-category pairs have been generated and displayed, and the top-N recommendations for a sample product have been produced, meeting all the specified requirements for your exam. This step will also include a brief evaluation context regarding the adaptation made for user identification.

## Summary:

### Q&A
The recommendation system, as specified, has been successfully built. The model has been trained (via Truncated SVD), predicted scores for product-category pairs have been generated and displayed, and top-N recommendations for a sample product have been produced. The adaptation for user identification by treating `product_title` as a user-like entity was implemented by using it as the index in the Product-Category Matrix.

### Data Analysis Key Findings
*   The dataset `/content/RS-A5_amazon_products_sales_data_cleaned.csv` was successfully loaded, and all required columns (`product_title`, `product_category`, `product_rating`) were confirmed to be present.
*   After dropping rows with missing values in the key columns, the dataset (`df_processed`) contained 31,314 rows and 17 columns.
*   `product_rating` was successfully scaled to a `Purchase_Score` between 0 and 1. For instance, a `product_rating` of 4.6 became a `Purchase_Score` of 0.900.
*   A 'Product-Category Matrix' was constructed with 8640 unique product titles and 15 unique product categories.
*   `TruncatedSVD` was applied with 10 components to generate latent factors.
*   The 'Product-Category Matrix' was reconstructed into `predicted_df`, a DataFrame of shape (8640, 15), containing predicted interaction scores for all product-category pairs.
*   A function `recommend_categories` was implemented to provide top-N recommendations. For a sample product `(2) Kicker 40PS692 6x9" 180w Polaris/ATV/UTV/RZR Marine Motorcycle Speakers PS69`, the top 5 recommended categories were Printers & Scanners, Laptops, Headphones, Speakers, and Gaming, all with a predicted score of 0.0000. This indicates that based on the SVD model with 10 components, these categories had the highest (albeit very low) predicted relevance for the given product after excluding already associated categories.

### Insights or Next Steps
*   The predicted scores for the sample product's recommendations were all 0.0000. This might suggest that the current SVD model with 10 components is not capturing fine-grained relationships or that the chosen product doesn't have strong predicted affinities to other categories after existing ones are filtered. Further analysis could involve experimenting with a higher number of SVD components or evaluating the distribution of predicted scores.
*   The current recommendation system provides category recommendations for products. A useful next step could be to extend this to recommend specific products within those recommended categories, or to incorporate other features like `total_reviews` or `discounted_price` to enhance the recommendation quality.

I understand! Let's simplify the explanation of the recommendation system built in the notebook using plain, straightforward language.

This project built a basic **Product Category Recommender System** using **Singular Value Decomposition (SVD)**, a technique similar to collaborative filtering, to suggest new product categories to a product's listing based on how similar products were rated in other categories.

---

## 🛠️ Step 1: Data Preparation and Scoring

The first job was to clean and prepare the product data to create a scoring system:

1.  **Define Roles:** We treated each **product title** as a unique "user" and each **product category** (like "Phones" or "Laptops") as an "item." The **product rating** was the "interaction score."
2.  **Clean Data:** We removed any entries where the title, category, or rating was missing.
3.  **Scale Ratings to Score:** The raw `product_rating` (1.0 to 5.0) was converted into a **`Purchase_Score`** between 0 and 1. This score represents the strength of the interaction (how much a product is "liked" within that category). A 5.0 rating became 1.0, and a 1.0 rating became 0.
4.  **Create the Matrix:** We organized this data into a huge table called the **Product-Category Matrix**.
    * **Rows:** Each row was a unique **product title** (the "user").
    * **Columns:** Each column was a unique **product category** (the "item").
    * **Values:** The cells contained the `Purchase_Score`. If a product wasn't in a category, the score was 0.

This resulting matrix had **8,640 products** (rows) and **15 categories** (columns).

---

## 🧠 Step 2: Learning with Truncated SVD

Next, we used a machine learning technique called **Truncated SVD** to find hidden patterns in the data.

1.  **Finding Latent Factors:** SVD broke down the large Product-Category Matrix into smaller, meaningful parts (like factors or features). It essentially learned **14 hidden characteristics** (latent factors) that explain why certain products score highly in certain categories.
    * *Think of it this way: a product rated highly in "Phones" and "Wearables" might score highly on a latent factor representing "Portable Personal Tech."*
2.  **Reconstruction and Prediction:** We then multiplied these learned parts back together. This didn't just re-create the original matrix; it filled in the "empty" cells (where the original score was 0) with a **predicted score**. The result was the **Predicted Interaction Scores (`predicted_df`)**.
    * **Significance:** This predicted score tells us how highly the model *thinks* a product would be rated in a category it is **not currently associated with**.

---

## 🎯 Step 3: Generating Recommendations

The final step was to use these predicted scores to give useful recommendations for a sample product:

1.  **Select a Product:** We picked a sample product (e.g., a **Kicker Speaker**).
2.  **Filter Out Existing Categories:** We looked at the predicted scores for this product in *all* 15 categories but **removed any categories** the product was already listed in (since you can't recommend what's already there).
3.  **Rank and Recommend:** The remaining categories were sorted by their predicted score (highest first). The **Top 5** categories with the highest predicted scores were returned as the recommendations.

For the sample Kicker Speaker, the model recommended categories like **Networking** and **Gaming**. Although the predicted scores were extremely low (close to zero), these were still the highest-ranked categories for that product based on the model's learned patterns.
"
"""