# -*- coding: utf-8 -*-
"""Sairaj4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nF7Vh4SsJ0l4oMBCq4T0nYagUSq3YkO6
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

# Load dataset
df = pd.read_csv('RS-A4_SEER Breast Cancer Dataset .csv')

# Clean column names
df.columns = df.columns.str.strip().str.replace('-', ' ').str.replace('_', ' ')
print("Columns:", df.columns.tolist())

# Handle missing values
imputer_cat = SimpleImputer(strategy='most_frequent')
imputer_num = SimpleImputer(strategy='mean')

# Define categorical columns - added 'T Stage'
cat_cols = ['Race', 'Marital Status', 'N Stage', '6th Stage',
            'Grade', 'A Stage', 'Estrogen Status', 'Progesterone Status', 'T Stage']

# Impute missing values for categorical columns
df[cat_cols] = imputer_cat.fit_transform(df[cat_cols])

# Encode categorical features column-wise
le = LabelEncoder()
for col in cat_cols:
    df[col] = le.fit_transform(df[col])

# Encode target variable
target_col = 'Status'
df[target_col] = le.fit_transform(df[target_col])

# Define X and y correctly
X = df.drop(columns=[target_col])
y = df[target_col]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Predict
y_pred = rf.predict(X_test)

# Evaluate
print(f"\nAccuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))